/**
 * Admin Conversations API Service (T-051)
 *
 * GET  /admin/conversations          → PaginatedResponse<ConversationSummaryVM>
 * GET  /admin/conversations/:id      → ConversationDetailVM
 * POST /admin/conversations/export   → { url: string }
 */

import { createAdminClient } from './client';
import type {
  ConversationSummaryVM,
  ConversationDetailVM,
  ConversationListParams,
} from '~/types/admin';
import type { PaginatedResponse, ApiResponse } from '~/types/api';

/**
 * List conversations with optional filters.
 * GET /admin/conversations
 */

export async function listConversations(
  params?: ConversationListParams,
): Promise<PaginatedResponse<ConversationSummaryVM>> {
  const client = createAdminClient();

  const res = await client<ApiResponse<PaginatedResponse<ConversationSummaryVM>>>(
    'admin/conversations',
    {
      method: 'GET',
      query: params,
    },
  );

  return res.data;
}

/**
 * Fetch the full detail of a single conversation.
 * GET /admin/conversations/:id
 */
export async function getConversationDetail(id: string): Promise<ConversationDetailVM> {
  const client = createAdminClient();
  const res = await client<ApiResponse<ConversationDetailVM>>(`admin/conversations/${id}`, {
    method: 'GET',
  });
  return res.data;
}

/**
 * Request a CSV/Excel export of conversations matching the given filters.
 * POST /admin/conversations/export
 * Returns a signed download URL generated by the backend.
 */
export async function exportConversations(
  params?: ConversationListParams,
): Promise<{ url: string }> {
  const client = createAdminClient();
  const res = await client<ApiResponse<{ url: string }>>('admin/conversations/export', {
    method: 'POST',
    body: params,
  });
  return res.data;
}
